# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18a009dd31a93136ecc63b0689cde20c7ad032a5cd21a904c4e47adf6ca88459058d36fa93fb9317278903129f2c6f536c7816ed05fc3b6f5e541ed4f7658431

test:
  secret_key_base: 5d64bc3a2e0f013f230bdca8522b3b5379d8d5bd0a1512583bdec14d983a606756e40d728f3b2a34809aa7c150c9b1bffb47206163960d8c132d0d78c28004c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
